### ISSUE TITLE
How can we set the parameters (dimensions) of qml to work correctly based on the dimensions of the input data, the number of classes?

### ISSUE THREAD

**Issue by CaiJichang212** [nicomeyer96/qiskit-torch-module#1]
How can we set the **parameters** (dimensions) of qml to work correctly based on **the dimensions of the input data**, **the number of classes**?
![image](https://github.com/nicomeyer96/qiskit-torch-module/assets/167088965/950d6cdd-949f-42c3-8aaa-f40eb44c59fb)
What is the relationship between input size,output size and other parameters?
Looking forward to your prompt reply!

**Comment by nicomeyer96** [comment]
### On "fixing" the code:

I think you have already set everything correctly, the problem is associated with the data loading itself. The QuantumModule expects a input of size 100 (i.e. **input_size**) in a flattened fashion, similar to e.g. a fully connected NN.

In the current form the training and test data is provided as ```[batch_size, 1, 10, 10]```, but we need ```[batch_size, 100]```. To achieve this you can just modify the transform to something like:
```python
transform = transforms.Compose([transforms.ToTensor(), transforms.Resize((10, 10)), torch.flatten])
``` 

With that modification everything should work as intended.

### On the different parameters of the QuantumModule:

- The **input_size** can not be explicitely set, but is defined by the circuit itself, i.e. how many ```encoding_params``` are used. This can be adjusted by either altering ```num_qubits```, ```depth```, or defining a custom circuit. The example you are using (assuming it is the ```generate_circuit``` method provided by us) realizes the incremental data uploading scheme described in [Incremental Data-Uploading for Full-Quantum Classification](https://ieeexplore.ieee.org/document/9951318).
- The **output_size** is defined by the number of measured obsevables. In the example the mode ```individualZ``` is used, which defaults to mwasuring single-qubit Pauli-Z observables on all qubits, i.e. 10 in this case. But it is also possible to define a custom list of ovservables.
- The number of **trainable** parameters is also defined by the employed VQC. In you example you have 11 layers (initial one plus depth), each with 20 parameters, summing up to the printed 220. This can also be altered by altering ```num_qubits```, ```depth```, or defining a custom circuit.

### On the HybridModule:

In you want more flexibility, the ```HybridModule``` might be an option. The VQC is embedded between two classical fully connected networks, allowing for combining arbitrary circuit layouts with arbitrary input and output dimensionalities.

Setting this up is straightforward with something like:
```python
model = HybridModule(
    vqc,  # an arbitrary quantum circuit
    encoding_params,  # (non-empty) list of VQC encoding parameters
    variational_params,  # (non-empty) list of VQC variational parameters
    input_size,  # feature dimensionality (e.g. 100 for above example)
    output_size,  # number of classes (e.g. 10 for above example)
)
```
With the ```HybridModule```, the number of ```encoding_params``` and the ```input_size``` can be completely independent.

**Comment by CaiJichang212** [comment]
Thank you very much. Your answer is very detailed. Your work has greatly inspired me, and I will cite your paper and work.

**Comment by nicomeyer96** [comment]
You're wecome, thanks a lot for the interest in our software framework! Looking forward to hearing about your work.

(Will mark the issue as resolved, just create a new one if there are more open problems / questions)
